spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    enabled-by-default: false

logging:
  level:
    root: INFO
    org.hibernate: ERROR
